class CountryItem {
  final String name;
  final String iso2;
  final String flagEmoji;
  final String phoneCode;

  const CountryItem({
    required this.name,
    required this.iso2,
    required this.flagEmoji,
    this.phoneCode = '',
  });
}

class CountriesData {
  static const List<CountryItem> all = [
    CountryItem(name: 'Afghanistan', iso2: 'AF', flagEmoji: '🇦🇫', phoneCode: '+93'),
    CountryItem(name: 'Albania', iso2: 'AL', flagEmoji: '🇦🇱', phoneCode: '+355'),
    CountryItem(name: 'Algeria', iso2: 'DZ', flagEmoji: '🇩🇿', phoneCode: '+213'),
    CountryItem(name: 'Andorra', iso2: 'AD', flagEmoji: '🇦🇩', phoneCode: '+376'),
    CountryItem(name: 'Angola', iso2: 'AO', flagEmoji: '🇦🇴', phoneCode: '+244'),
    CountryItem(name: 'Argentina', iso2: 'AR', flagEmoji: '🇦🇷', phoneCode: '+54'),
    CountryItem(name: 'Armenia', iso2: 'AM', flagEmoji: '🇦🇲', phoneCode: '+374'),
    CountryItem(name: 'Australia', iso2: 'AU', flagEmoji: '🇦🇺', phoneCode: '+61'),
    CountryItem(name: 'Austria', iso2: 'AT', flagEmoji: '🇦🇹', phoneCode: '+43'),
    CountryItem(name: 'Azerbaijan', iso2: 'AZ', flagEmoji: '🇦🇿', phoneCode: '+994'),
    CountryItem(name: 'Bahamas', iso2: 'BS', flagEmoji: '🇧🇸', phoneCode: '+1242'),
    CountryItem(name: 'Bahrain', iso2: 'BH', flagEmoji: '🇧🇭', phoneCode: '+973'),
    CountryItem(name: 'Bangladesh', iso2: 'BD', flagEmoji: '🇧🇩', phoneCode: '+880'),
    CountryItem(name: 'Barbados', iso2: 'BB', flagEmoji: '🇧🇧', phoneCode: '+1246'),
    CountryItem(name: 'Belarus', iso2: 'BY', flagEmoji: '🇧🇾', phoneCode: '+375'),
    CountryItem(name: 'Belgium', iso2: 'BE', flagEmoji: '🇧🇪', phoneCode: '+32'),
    CountryItem(name: 'Belize', iso2: 'BZ', flagEmoji: '🇧🇿', phoneCode: '+501'),
    CountryItem(name: 'Benin', iso2: 'BJ', flagEmoji: '🇧🇯', phoneCode: '+229'),
    CountryItem(name: 'Bhutan', iso2: 'BT', flagEmoji: '🇧🇹', phoneCode: '+975'),
    CountryItem(name: 'Bolivia', iso2: 'BO', flagEmoji: '🇧🇴', phoneCode: '+591'),
    CountryItem(name: 'Bosnia and Herzegovina', iso2: 'BA', flagEmoji: '🇧🇦', phoneCode: '+387'),
    CountryItem(name: 'Botswana', iso2: 'BW', flagEmoji: '🇧🇼', phoneCode: '+267'),
    CountryItem(name: 'Brazil', iso2: 'BR', flagEmoji: '🇧🇷', phoneCode: '+55'),
    CountryItem(name: 'Brunei', iso2: 'BN', flagEmoji: '🇧🇳', phoneCode: '+673'),
    CountryItem(name: 'Bulgaria', iso2: 'BG', flagEmoji: '🇧🇬', phoneCode: '+359'),
    CountryItem(name: 'Burkina Faso', iso2: 'BF', flagEmoji: '🇧🇫', phoneCode: '+226'),
    CountryItem(name: 'Burundi', iso2: 'BI', flagEmoji: '🇧🇮', phoneCode: '+257'),
    CountryItem(name: 'Cambodia', iso2: 'KH', flagEmoji: '🇰🇭', phoneCode: '+855'),
    CountryItem(name: 'Cameroon', iso2: 'CM', flagEmoji: '🇨🇲', phoneCode: '+237'),
    CountryItem(name: 'Canada', iso2: 'CA', flagEmoji: '🇨🇦', phoneCode: '+1'),
    CountryItem(name: 'Chile', iso2: 'CL', flagEmoji: '🇨🇱', phoneCode: '+56'),
    CountryItem(name: 'China', iso2: 'CN', flagEmoji: '🇨🇳', phoneCode: '+86'),
    CountryItem(name: 'Colombia', iso2: 'CO', flagEmoji: '🇨🇴', phoneCode: '+57'),
    CountryItem(name: 'Costa Rica', iso2: 'CR', flagEmoji: '🇨🇷', phoneCode: '+506'),
    CountryItem(name: 'Croatia', iso2: 'HR', flagEmoji: '🇭🇷', phoneCode: '+385'),
    CountryItem(name: 'Cuba', iso2: 'CU', flagEmoji: '🇨🇺', phoneCode: '+53'),
    CountryItem(name: 'Cyprus', iso2: 'CY', flagEmoji: '🇨🇾', phoneCode: '+357'),
    CountryItem(name: 'Czech Republic', iso2: 'CZ', flagEmoji: '🇨🇿', phoneCode: '+420'),
    CountryItem(name: 'Denmark', iso2: 'DK', flagEmoji: '🇩🇰', phoneCode: '+45'),
    CountryItem(name: 'Dominican Republic', iso2: 'DO', flagEmoji: '🇩🇴', phoneCode: '+1809'),
    CountryItem(name: 'Ecuador', iso2: 'EC', flagEmoji: '🇪🇨', phoneCode: '+593'),
    CountryItem(name: 'Egypt', iso2: 'EG', flagEmoji: '🇪🇬', phoneCode: '+20'),
    CountryItem(name: 'Estonia', iso2: 'EE', flagEmoji: '🇪🇪', phoneCode: '+372'),
    CountryItem(name: 'Ethiopia', iso2: 'ET', flagEmoji: '🇪🇹', phoneCode: '+251'),
    CountryItem(name: 'Fiji', iso2: 'FJ', flagEmoji: '🇫🇯', phoneCode: '+679'),
    CountryItem(name: 'Finland', iso2: 'FI', flagEmoji: '🇫🇮', phoneCode: '+358'),
    CountryItem(name: 'France', iso2: 'FR', flagEmoji: '🇫🇷', phoneCode: '+33'),
    CountryItem(name: 'Georgia', iso2: 'GE', flagEmoji: '🇬🇪', phoneCode: '+995'),
    CountryItem(name: 'Germany', iso2: 'DE', flagEmoji: '🇩🇪', phoneCode: '+49'),
    CountryItem(name: 'Ghana', iso2: 'GH', flagEmoji: '🇬🇭', phoneCode: '+233'),
    CountryItem(name: 'Greece', iso2: 'GR', flagEmoji: '🇬🇷', phoneCode: '+30'),
    CountryItem(name: 'Guatemala', iso2: 'GT', flagEmoji: '🇬🇹', phoneCode: '+502'),
    CountryItem(name: 'Honduras', iso2: 'HN', flagEmoji: '🇭🇳', phoneCode: '+504'),
    CountryItem(name: 'Hong Kong', iso2: 'HK', flagEmoji: '🇭🇰', phoneCode: '+852'),
    CountryItem(name: 'Hungary', iso2: 'HU', flagEmoji: '🇭🇺', phoneCode: '+36'),
    CountryItem(name: 'Iceland', iso2: 'IS', flagEmoji: '🇮🇸', phoneCode: '+354'),
    CountryItem(name: 'India', iso2: 'IN', flagEmoji: '🇮🇳', phoneCode: '+91'),
    CountryItem(name: 'Indonesia', iso2: 'ID', flagEmoji: '🇮🇩', phoneCode: '+62'),
    CountryItem(name: 'Iran', iso2: 'IR', flagEmoji: '🇮🇷', phoneCode: '+98'),
    CountryItem(name: 'Iraq', iso2: 'IQ', flagEmoji: '🇮🇶', phoneCode: '+964'),
    CountryItem(name: 'Ireland', iso2: 'IE', flagEmoji: '🇮🇪', phoneCode: '+353'),
    CountryItem(name: 'Israel', iso2: 'IL', flagEmoji: '🇮🇱', phoneCode: '+972'),
    CountryItem(name: 'Italy', iso2: 'IT', flagEmoji: '🇮🇹', phoneCode: '+39'),
    CountryItem(name: 'Jamaica', iso2: 'JM', flagEmoji: '🇯🇲', phoneCode: '+1876'),
    CountryItem(name: 'Japan', iso2: 'JP', flagEmoji: '🇯🇵', phoneCode: '+81'),
    CountryItem(name: 'Jordan', iso2: 'JO', flagEmoji: '🇯🇴', phoneCode: '+962'),
    CountryItem(name: 'Kazakhstan', iso2: 'KZ', flagEmoji: '🇰🇿', phoneCode: '+7'),
    CountryItem(name: 'Kenya', iso2: 'KE', flagEmoji: '🇰🇪', phoneCode: '+254'),
    CountryItem(name: 'Kuwait', iso2: 'KW', flagEmoji: '🇰🇼', phoneCode: '+965'),
    CountryItem(name: 'Latvia', iso2: 'LV', flagEmoji: '🇱🇻', phoneCode: '+371'),
    CountryItem(name: 'Lebanon', iso2: 'LB', flagEmoji: '🇱🇧', phoneCode: '+961'),
    CountryItem(name: 'Lithuania', iso2: 'LT', flagEmoji: '🇱🇹', phoneCode: '+370'),
    CountryItem(name: 'Luxembourg', iso2: 'LU', flagEmoji: '🇱🇺', phoneCode: '+352'),
    CountryItem(name: 'Malaysia', iso2: 'MY', flagEmoji: '🇲🇾', phoneCode: '+60'),
    CountryItem(name: 'Maldives', iso2: 'MV', flagEmoji: '🇲🇻', phoneCode: '+960'),
    CountryItem(name: 'Malta', iso2: 'MT', flagEmoji: '🇲🇹', phoneCode: '+356'),
    CountryItem(name: 'Mauritius', iso2: 'MU', flagEmoji: '🇲🇺', phoneCode: '+230'),
    CountryItem(name: 'Mexico', iso2: 'MX', flagEmoji: '🇲🇽', phoneCode: '+52'),
    CountryItem(name: 'Monaco', iso2: 'MC', flagEmoji: '🇲🇨', phoneCode: '+377'),
    CountryItem(name: 'Mongolia', iso2: 'MN', flagEmoji: '🇲🇳', phoneCode: '+976'),
    CountryItem(name: 'Morocco', iso2: 'MA', flagEmoji: '🇲🇦', phoneCode: '+212'),
    CountryItem(name: 'Myanmar', iso2: 'MM', flagEmoji: '🇲🇲', phoneCode: '+95'),
    CountryItem(name: 'Nepal', iso2: 'NP', flagEmoji: '🇳🇵', phoneCode: '+977'),
    CountryItem(name: 'Netherlands', iso2: 'NL', flagEmoji: '🇳🇱', phoneCode: '+31'),
    CountryItem(name: 'New Zealand', iso2: 'NZ', flagEmoji: '🇳🇿', phoneCode: '+64'),
    CountryItem(name: 'Nigeria', iso2: 'NG', flagEmoji: '🇳🇬', phoneCode: '+234'),
    CountryItem(name: 'Norway', iso2: 'NO', flagEmoji: '🇳🇴', phoneCode: '+47'),
    CountryItem(name: 'Oman', iso2: 'OM', flagEmoji: '🇴🇲', phoneCode: '+968'),
    CountryItem(name: 'Pakistan', iso2: 'PK', flagEmoji: '🇵🇰', phoneCode: '+92'),
    CountryItem(name: 'Panama', iso2: 'PA', flagEmoji: '🇵🇦', phoneCode: '+507'),
    CountryItem(name: 'Peru', iso2: 'PE', flagEmoji: '🇵🇪', phoneCode: '+51'),
    CountryItem(name: 'Philippines', iso2: 'PH', flagEmoji: '🇵🇭', phoneCode: '+63'),
    CountryItem(name: 'Poland', iso2: 'PL', flagEmoji: '🇵🇱', phoneCode: '+48'),
    CountryItem(name: 'Portugal', iso2: 'PT', flagEmoji: '🇵🇹', phoneCode: '+351'),
    CountryItem(name: 'Qatar', iso2: 'QA', flagEmoji: '🇶🇦', phoneCode: '+974'),
    CountryItem(name: 'Romania', iso2: 'RO', flagEmoji: '🇷🇴', phoneCode: '+40'),
    CountryItem(name: 'Russia', iso2: 'RU', flagEmoji: '🇷🇺', phoneCode: '+7'),
    CountryItem(name: 'Rwanda', iso2: 'RW', flagEmoji: '🇷🇼', phoneCode: '+250'),
    CountryItem(name: 'Saudi Arabia', iso2: 'SA', flagEmoji: '🇸🇦', phoneCode: '+966'),
    CountryItem(name: 'Senegal', iso2: 'SN', flagEmoji: '🇸🇳', phoneCode: '+221'),
    CountryItem(name: 'Serbia', iso2: 'RS', flagEmoji: '🇷🇸', phoneCode: '+381'),
    CountryItem(name: 'Singapore', iso2: 'SG', flagEmoji: '🇸🇬', phoneCode: '+65'),
    CountryItem(name: 'Slovakia', iso2: 'SK', flagEmoji: '🇸🇰', phoneCode: '+421'),
    CountryItem(name: 'Slovenia', iso2: 'SI', flagEmoji: '🇸🇮', phoneCode: '+386'),
    CountryItem(name: 'South Africa', iso2: 'ZA', flagEmoji: '🇿🇦', phoneCode: '+27'),
    CountryItem(name: 'South Korea', iso2: 'KR', flagEmoji: '🇰🇷', phoneCode: '+82'),
    CountryItem(name: 'Spain', iso2: 'ES', flagEmoji: '🇪🇸', phoneCode: '+34'),
    CountryItem(name: 'Sri Lanka', iso2: 'LK', flagEmoji: '🇱🇰', phoneCode: '+94'),
    CountryItem(name: 'Sweden', iso2: 'SE', flagEmoji: '🇸🇪', phoneCode: '+46'),
    CountryItem(name: 'Switzerland', iso2: 'CH', flagEmoji: '🇨🇭', phoneCode: '+41'),
    CountryItem(name: 'Taiwan', iso2: 'TW', flagEmoji: '🇹🇼', phoneCode: '+886'),
    CountryItem(name: 'Tanzania', iso2: 'TZ', flagEmoji: '🇹🇿', phoneCode: '+255'),
    CountryItem(name: 'Thailand', iso2: 'TH', flagEmoji: '🇹🇭', phoneCode: '+66'),
    CountryItem(name: 'Tunisia', iso2: 'TN', flagEmoji: '🇹🇳', phoneCode: '+216'),
    CountryItem(name: 'Turkey', iso2: 'TR', flagEmoji: '🇹🇷', phoneCode: '+90'),
    CountryItem(name: 'Uganda', iso2: 'UG', flagEmoji: '🇺🇬', phoneCode: '+256'),
    CountryItem(name: 'Ukraine', iso2: 'UA', flagEmoji: '🇺🇦', phoneCode: '+380'),
    CountryItem(name: 'United Arab Emirates', iso2: 'AE', flagEmoji: '🇦🇪', phoneCode: '+971'),
    CountryItem(name: 'United Kingdom', iso2: 'GB', flagEmoji: '🇬🇧', phoneCode: '+44'),
    CountryItem(name: 'United States', iso2: 'US', flagEmoji: '🇺🇸', phoneCode: '+1'),
    CountryItem(name: 'Uruguay', iso2: 'UY', flagEmoji: '🇺🇾', phoneCode: '+598'),
    CountryItem(name: 'Uzbekistan', iso2: 'UZ', flagEmoji: '🇺🇿', phoneCode: '+998'),
    CountryItem(name: 'Venezuela', iso2: 'VE', flagEmoji: '🇻🇪', phoneCode: '+58'),
    CountryItem(name: 'Vietnam', iso2: 'VN', flagEmoji: '🇻🇳', phoneCode: '+84'),
    CountryItem(name: 'Zambia', iso2: 'ZM', flagEmoji: '🇿🇲', phoneCode: '+260'),
    CountryItem(name: 'Zimbabwe', iso2: 'ZW', flagEmoji: '🇿🇼', phoneCode: '+263'),
  ];

  static String getFlag(String countryName) {
    if (countryName.isEmpty) return '🌐';
    final match = all.firstWhere(
      (c) => c.name.toLowerCase() == countryName.trim().toLowerCase(),
      orElse: () => const CountryItem(name: '', iso2: '', flagEmoji: '📍'),
    );
    return match.flagEmoji;
  }
}
