-- ======================================================================
-- MLM BOOK - COMPLETE DATABASE TIMESTAMP -> DATETIME CONVERSION SCRIPT
-- Target Timezone: Asia/Kolkata (IST, UTC+05:30)
-- Total Base Table Timestamp Columns: 135
-- Date: 2026-09-28 11:19:52
-- ======================================================================

SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '+05:30';

ALTER TABLE `admins` MODIFY `last_login_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `admins` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `admins` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `admin_roles` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `admin_roles` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `ad_deposits` MODIFY `submitted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `ad_deposits` MODIFY `verified_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_analytics_views` MODIFY `viewed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `business_conversations` MODIFY `last_message_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_followers` MODIFY `followed_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_invitations` MODIFY `expires_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_messages` MODIFY `read_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_pages` MODIFY `deleted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_review_replies` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_review_replies` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_review_reports` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_review_reports` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_review_votes` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_review_votes` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_team_members` MODIFY `joined_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_team_members` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_team_members` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_verifications` MODIFY `reviewed_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_verifications` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `business_verifications` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `categories` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `categories` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `comment_reactions` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `comment_reactions` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `communities` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `communities` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `communities` MODIFY `deleted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_audit_logs` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_audit_logs` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_bans` MODIFY `expires_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_bans` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_bans` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_invitations` MODIFY `expires_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_invitations` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_invitations` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_members` MODIFY `muted_until` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_members` MODIFY `joined_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_members` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_members` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_reports` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_reports` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_warnings` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `community_warnings` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `direct_messages` MODIFY `read_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `direct_messages` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `direct_messages` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `events` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `events` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `event_invitations` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `event_invitations` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `event_responses` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `event_responses` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `failed_jobs` MODIFY `failed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `feedback_suggestions` MODIFY `responded_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `feedback_suggestions` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `feedback_suggestions` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `followers` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `followers` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `friendships` MODIFY `accepted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `friendships` MODIFY `rejected_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `friendships` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `friendships` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `groups` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `groups` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `group_invitations` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `group_invitations` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `group_members` MODIFY `joined_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `group_members` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `group_members` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `hidden_posts` MODIFY `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `import_funds` MODIFY `verified_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `import_funds` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `import_funds` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `member_verification_otps` MODIFY `verified_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `member_verification_otps` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `member_verification_otps` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `notifications` MODIFY `read_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `notifications` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `notifications` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `password_reset_tokens` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `pending_member_registrations` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `pending_member_registrations` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `permissions` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `permissions` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_comments` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_comments` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_comments` MODIFY `deleted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_likes` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_likes` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_reactions` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_reactions` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_shares` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `post_shares` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `products` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `products` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `product_media` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `product_media` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `profile_visits` MODIFY `visited_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `profile_visits` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `profile_visits` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `reported_posts` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `reported_posts` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `reported_products` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `reported_products` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `reward_rank_rules` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `reward_rank_rules` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `roles` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `roles` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `role_permissions` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `role_permissions` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `saved_posts` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `saved_posts` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `saved_products` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `saved_products` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `settings` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `settings` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_likes` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_likes` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_reactions` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_reactions` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_replies` MODIFY `deleted_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_replies` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_replies` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_views` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `story_views` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `users` MODIFY `email_verified_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `users` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `users` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `withdrawal_settings` MODIFY `created_at` DATETIME NULL DEFAULT NULL;
ALTER TABLE `withdrawal_settings` MODIFY `updated_at` DATETIME NULL DEFAULT NULL;
